### ISSUE TITLE
Tests don't work

### ISSUE THREAD

**Issue by aleksei-commmune** [shubhbapna/mock-github-act-js-examples#1]
All examples failed

**Comment by shubhbapna** [comment]
Hi there! I have updated the test cases to the latest version of `act-js` and `mock-github`.  It seems to be working in CI.

Could you try running them now? If there are still some errors, can please describe what the error message is? Furthermore for each example you can get a log file with the raw out of act by setting `ACT_LOG=true`. Could you share those logs as well?

**Comment by aleksei-commmune** [comment]
Thank you for the quick reply!

The error is:

```
Errors .../mock-github-act-js-examples/workflow/simple/node_modules/@kie/act-js/build/bin/act:
.../mock-github-act-js-examples/workflow/simple/node_modules/@kie/act-js/build/bin/act: cannot execute binary file
```

I think it's not related to the examples, but to the `act-js` itself since `npx act-js` prints the same error

Apple M1 Ventura 13.0
node: v16.15.0
git: 2.40.0

**Comment by aleksei-commmune** [comment]
I fixed it by using my local version of `act` by exporting `ACT_BINARY`, so probably there is an issue with the act binary provided with the package, should I create an issue at the act-js repo?

**Comment by shubhbapna** [comment]
Oh I see. Yes please can you open an issue in act-js?
